### ISSUE TITLE
Execute bicep file with subscription deployment mode

### ISSUE THREAD

**Issue by leandromsft** [Azure/arm-deploy#112]
Hello,

I create a bicep file to create a resource group and other resources within this resource group
This bicep file works fine when I execute using **az deployment sub create** command

So, I create GitHub workflow to automate my bice file execution, as fallow:

```    
     # Checkout code
      - name: Checkout aspnetcoreiac
        uses: actions/checkout@v3
        with:
          path: src/aspnetcoreiac
      
      # Log into Azure
      - name: Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: Deploy Template
        uses: Azure/arm-deploy@v1.0.8
        with:
          scope: subscription
          region: ${{ env.AZ_RG_LOCATION }}
          template: src/aspnetcoreiac/main.bicep
          deploymentMode: Incremental
          deploymentName: 'gh-actions'
          parameters: rgName=${{ env.AZ_RG_NAME }} rgLocation=${{ env.AZ_RG_LOCATION }} acrName=${{ env.AZ_ACR_NAME }} clusterName=${{ env.AZ_AKS_NAME }} sqlserverName=${{ env.AZ_SQLSERVER_NAME }}
          failOnStdErr: false
```

But when the workflow run, result this warning:

```
Warning: This deployment mode is not supported for subscription scoped deployments, this parameter will be ignored!
Validating template...
Warning: ERROR: An error occurred reading file. Could not find file '/home/runner/work/dotnet-container-app/dotnet-container-app/src/aspnetcoreiac/main.bicep'.
```

So, my questions is: How I can automatically run my bicep files in the subscription scope?

Thank you

**Comment by t-dedah** [comment]
Hi @leandromsft the workflow file looks okay to me. 
Can you please confirm if the path `/home/runner/work/dotnet-container-app/dotnet-container-app/src/aspnetcoreiac/main.bicep` is correct ?

If yes, then can you also add few more commands like `ls -a` and `pwd` just to check if the file still exists in the directory?
```yml
- name: Script
  run : | 
    ls -a
    pwd
```
