### ISSUE TITLE
ERROR: InvalidTemplate - Deployment template validation failed: 'The template resource '_artifactsLocation'

### ISSUE THREAD

**Issue by rx007** [Azure/arm-deploy#113]
Hello,

Below is my github actions deployment, but still getting an error. Anybody can help me? Thank you!
```
deploy:
  name: Deploy
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Azure Cloud
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: group1
        template: azure/templates/armdeploy.json
        parameters: azure/templates/armdeploy.parameters.json 
        additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
```

armdeploy.json
```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
      "_artifactsLocation": {
          "type": "string",
          "defaultValue": "[deployment().properties.templateLink.uri]",
          "metadata": {
              "description": "The base URI where artifacts required by this template are located, including a trailing '/'"
          }
      },
      "_artifactsLocationSasToken": {
          "type": "securestring",
          "defaultValue": "",
          "metadata": {
              "description": "The sasToken required to access _artifactsLocation. When the template is deployed using the accompanying scripts, a sasToken will be automatically generated. Use the defaultValue if the staging location is not secured."
          }
      },
```

error
```
ERROR: InvalidTemplate - Deployment template validation failed: 'The template resource '_artifactsLocation' at line '1' and column '182' is not valid: The language expression property 'templateLink' doesn't exist, available properties are 'template, templateHash, parameters, mode, provisioningState'.. Please see https://aka.ms/arm-template-expressions for usage details.'.
```
