### ISSUE TITLE
Getting this error when using parameters: Warning: WARNING: The configuration value of bicep.use_binary_from_path has been set to 'false'.

### ISSUE THREAD

**Issue by roldengarm** [Azure/arm-deploy#173]
Initially I passed all parameters inline, all was fine. After I added a .bicepparam file & supplied that for the parameters parameter of the action, I get this warning:
```
Warning: WARNING: The configuration value of bicep.use_binary_from_path has been set to 'false'.
```

Works fine:
```
      - name: deploy
        uses: azure/arm-deploy@v2
        id: deploy
        with:
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ vars.AZURE_RG }}
          template: ./infrastructure/main.bicep
          scope: resourcegroup
          parameters: 'param1=PARAM1 param2=PARAM2'
          failOnStdErr: false
```
Warning occurs with:
```
      - name: deploy
        uses: azure/arm-deploy@v2
        id: deploy
        with:
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ vars.AZURE_RG }}
          template: ./infrastructure/main.bicep
          scope: resourcegroup
          parameters: './infrastructure/main.bicepparam'
          failOnStdErr: false
```
