### ISSUE TITLE
Cannot use array parameter

### ISSUE THREAD

**Issue by vRune4** [Azure/arm-deploy#214]
(Similar to other open issues, but maybe I can describe this a little better)

```yaml
- name: 🚀 Deploy to development environment (subscription scope)
  uses: azure/arm-deploy@v2
  with:
    scope: subscription
    subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    failOnStdErr: false # https://github.com/Azure/arm-deploy/issues/126
    region: Norway East
    template: ./main.bicep
    parameters: >
      ipList=${{vars.IPLIST}}
```

If I try:
`gh variable set IPLIST --env dev --body '{[ ["Somewhere", "xx.yy.zz.xx"], ["Somewhere else", "xx.yy.zz.xx"]  ]}'`

What is logged:
`ipList={[ ["Somewhere", "xx.yy.zz.xx"], ["Somewhere else", "xx.yy.zz.xx"]  ]}`

> Error: ERROR: Failed to parse string as JSON:
> {[
> Error detail: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

This should work:
`gh variable set IPLIST --env dev --body '[ ["Somewhere", "xx.yy.zz.xx"], ["Somewhere else", "xx.yy.zz.xx"]  ]'`

`ipList=[ ["Somewhere", "xx.yy.zz.xx"], ["Somewhere else", "xx.yy.zz.xx"]  ]`

> Error: ERROR: Failed to parse string as JSON:
> [
> Error detail: Expecting value: line 1 column 2 (char 1)

Try with a surrounding quote:
`gh variable set IPLIST --env dev --body '''[ ["Somewhere", "xx.yy.zz.xx"], ["Somewhere else", "xx.yy.zz.xx"] ]'''`

`ipList='[ ["Somewhere", "xx.yy.zz.xx"], ["Somewhere else", "xx.yy.zz.xx"]  ]'`

> Error: ERROR: Failed to parse string as JSON:
> '[
> Error detail: Expecting value: line 1 column 1 (char 0)
> 

The json parameter files look promising. Try putting that into a string:
`gh variable set IPLIST --env dev --body '{"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#", "contentVersion": "1.0.0.0", "parameters": {"iplist": { "value": [["", ""] ]}}}'`

What follows is what is passed on to the action. Notice that $schema is still inside double quotes:
`ipList={"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#", "contentVersion": "1.0.0.0", "parameters": {"iplist": { "value": [["", ""] ]}}}`

> Error: ERROR: Failed to parse string as JSON:
> {$schema:
> Error detail: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

Escape the quotes?
`ipList={\"$schema\": \"https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#\", \"contentVersion\": \"1.0.0.0\", \"parameters\": {\"iplist\": { \"value\": [[\"\", \"\"] ]}}}`

> Error: ERROR: Failed to parse string as JSON:
> {\$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#", "contentVersion": "1.0.0.0", "parameters": {"iplist": { "value": [["", ""] ]}}} -o json
> Error detail: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

So now it is randomly dropping characters from the input. The parser needs work.

The "json parameter file as a string" approach is just desperation on my part. I am definitively barking up the wrong tree. A workaround would be to have separate json parameter files for each environment, but cannot use that approach with secrets.
