### ISSUE TITLE
Error: The process '/usr/bin/az' failed with exit code 2

### ISSUE THREAD

**Issue by FBoucher** [Azure/arm-deploy#30]
The deployment using Az CLI works but fails when using the action.  Maybe it's obvious but I don't see what I'm doing wrong...

So in my GitHub Action this will works perfectly

```yaml
   - uses: azure/login@v1
      with:
        creds: ${{ secrets.GR_azUrlGitHubDev_CREDENTIALS }}

    - run: |
        az group deployment create -n github-dev -g UrlShortnerDEV --template-file deployment/azureDeploy.json --parameters "deployment/azureDeploy.params.dev.json"
```

but this fails (I'm using the same everything, paths, names, creds)

```yaml
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: UrlShortnerDEV
        deploymentName: github-dev
        template: deployment/azureDeploy.json
        parameters: deployment/azureDeploy.params.dev.json
```

Here the error message:

```
Run azure/arm-deploy@v1
  with:
    deploymentMode: Validate
    resourceGroupName: UrlShortnerDEV
    deploymentName: github-dev
    template: ./deployment/azureDeploy.json
    parameters: ./deployment/azureDeploy.params.dev.json
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
Changing subscription context...
Error: The process '/usr/bin/az' failed with exit code 2
```

Any Idea?

**Comment by wiebeck** [comment]
Exact same issue here. :-/

**Comment by MarcBruins** [comment]
Can confirm that the workaround is setting a hard value for the `subscriptionId`.

**Comment by FBoucher** [comment]
@MarcBruins adding the `subscriptionId` didn't fixed the problem for me

**Comment by MarcBruins** [comment]
Mm weird. This is what i changed:
```` 
- uses: azure/arm-deploy@v1.0.1
      with:
        resourceGroupName: rgName
        template: IAC/template.json
        parameters: IAC/parameters.json
````

to:

```` 
- uses: azure/arm-deploy@v1.0.1
      with:
        resourceGroupName: rgName
        template: IAC/template.json
        parameters: IAC/parameters.json
        subscriptionId : 8a5498fc-90e9-401c-a942-146582942c1b
````
