### ISSUE TITLE
Allow to create resource group

### ISSUE THREAD

**Issue by fvilches17** [Azure/arm-deploy#32]
This action seems to only work if the resource group has been created previously.

As a workaround one has to either go to the azure portal and manually create the resource group or add a previous workflow step to automate the creation of the resource group (e.g. using azure cli to create the rg).

It would be nice to be able to create (assuming it's the first run) the resource group or update the resource group.

Example: See the Azure DevOps equivalent. See option 'Create or Update Resource Group'

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#yaml-snippet

**Comment by fvilches17** [comment]
To further add, here's my workaround. I added a script to ensure the resource group is created beforehand. 

So perhaps instead of enhancing the current action,  the docs and/or sample yaml code could have previous optional action like this one? Or even better, howabout create an azure action just for creating a resource group? Thus, sticking to separation of concerns.

Although, one thing to consider is that this will only work if you took a more generic approach when creating your azure credentials for use in the "Azure Login" action. 

At time of writing, the Azure Login Action doc recommends being granular and either scoping like {subscriptionid}/{resourcegroup}/{webapp} or {subscriptionid}/{resourcegroup}

However, in order to be able to create a resource group, you have to be less granular and scope at the {subscriptionid}/* level.

![image](https://user-images.githubusercontent.com/13502806/107327924-cbefb600-6b12-11eb-97f8-fc9b1b8cf56a.png)

**Comment by kanika1894** [comment]
This is a feature request.
Looping @pulkitaggarwl for better clarity.

**Comment by pulkitaggarwl** [comment]
@fvilches17 thanks for reaching out 

> So perhaps instead of enhancing the current action, the docs and/or sample yaml code could have previous optional action like this one? 

we are aligned here. It needs to be done to keep separations of concerns in mind. 
Both these are valid alternatives, however, for just resource group creation, a script may be a better alternative. Whats your thoughts on this? 

Also, would you like to raise a PR against the action documentation with the suggested enhancements ?

**Comment by fvilches17** [comment]
> we are aligned here. It needs to be done to keep separations of concerns in mind.
> Both these are valid alternatives, however, for just resource group creation, a script may be a better alternative. Whats your thoughts on this?
> 
> Also, would you like to raise a PR against the action documentation with the suggested enhancements ?

Hi @pulkitaggarwl,

Yes agree. Even though in Azure DevOps the equivalent task combines both tasks (create rg + arm deploy), it would be a cleaner approach to keep this task separate.

As such, is there already in the roadmap a dedicated Azure GitHub action for creating resource groups?

E.g.

```
- name: Azure Login
   uses: Azure/login@v1
   with:
      creds: ${{ secrets.AZURE_CREDENTIALS }} #scope at subscription level {subscriptionid}/* see [https://github.com/marketplace/actions/azure-login#configure-deployment-credentials](url)
          enable-AzPSSession: true
      
- name: Ensure Azure Resource Group Created
   uses: Azure/resourceGroup@v1
   with:
      rgName: {string} #required
      region: {string} #required
      tags: {key1=value1 key2=value2 etc} #optional
```

If not already being developed, I might just explore creating a PR for this action 👆

Ps, yes in the meantime I can a raise a PR to add an optional resource group creation script before the arm deploy task
