### ISSUE TITLE
JSON array as parameter input

### ISSUE THREAD

**Issue by dpantaz** [Azure/arm-deploy#36]
Hello.

Is it possible to use a JSON array as a parameter value in the parameters input?
For example
parameters: param1=<JSON array from file read in previous step>

Thank you.

**Comment by marvinbuss** [comment]
@bishal-pdMSFT We are running into issues, when trying to do this. Due to the `AZURE_CREDENTIALS`, it also seems like that any `{` and `}` get replaced with `***` in the Actions page and passing a JSON array always fails with `Failed to parse JSON`. Here are more details:
![image](https://user-images.githubusercontent.com/34542414/117373549-bc8ec780-aecb-11eb-98a2-a0d1af79b59e.png)

**Comment by t-dedah** [comment]
Hi @marvinbuss, will it be possible to please share the exact parameter input. Are you passing a json or a json string something like this
_'{\"costCenter\":\"ABCD\", \"owner\":\"XYZ\"}'_

**Comment by marvinbuss** [comment]
Hi @t-dedah, I am passing a JSON string as input (e.g. `'{"costCenter":"ABCD", "owner":"XYZ"}'`). `{` gets replaced with `***` it seems. Using a JSON as secret is also not recommended by the Actions team. We should consider moving to a different auth method with individual secrets for clientId and clientSecret. See here: https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-secrets

**Comment by t-dedah** [comment]
@marvinbuss I am little confused. What secrets are you trying to pass as parameters? shouldn't we use azure login task for that? Also I consoled out `'{"costCenter":"ABCD", "owner":"XYZ"}'` and everything looks okay to me.

Will it be possible to share repro steps for the issue?

![Screenshot 2021-05-19 at 3 43 55 PM](https://user-images.githubusercontent.com/59823596/118796491-4b7ee500-b8b9-11eb-9762-29ff9479799d.png)

**Comment by marvinbuss** [comment]
Please try this workflow:

```
name: Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/**'

env:
  AZURE_SUBSCRIPTION_ID: 'your-sub-id'
  AZURE_LOCATION: 'northeurope'
  AZURE_TAGS: '{"costCenter":"ABCD", "owner":"XYZ"}'

jobs:
  create-resource-groups:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Deploy Resource Groups
    - name: Deploy Resource Groups
      id: resource_groups_deployment
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/ResourceGroups/deploy.resourceGroups.json
        parameters: ${{ github.workspace }}/infra/ResourceGroups/params.resourceGroups.json tags='${{ env.AZURE_TAGS }}'
    
    # Log out from Azure
    - name: Log out from Azure
      id: azure_logout
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az logout
```
