### ISSUE TITLE
azure/arm-deploy@v1 fails after new release of Azure CLI Version 2.24.1

### ISSUE THREAD

**Issue by JaMatus** [Azure/arm-deploy#48]
Hello 🙂 Since the new release (1. June 2021) of Azure CLI Version 2.24.1, our github actions deployment to azure fails on azure/arm-deploy@v1 with following error:

The process 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd' failed because one or more lines were written to the STDERR stream

Have you experienced similar problem or this is not related in your opinion? 

Thanks

**Comment by mburuckercSO** [comment]
We are running into a similar issue on Linux runners.
`The process '/usr/bin/az' failed because one or more lines were written to the STDERR stream`

**Comment by t-dedah** [comment]
@mburuckercSO @JaMatus Can you please share the workflow file?

**Comment by blue-lemons-sk** [comment]
@t-dedah sure 🙂 here is the release workflow file:

`name: DEV .NET Core CD ARM template

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{env.DOTNET_ROOT}}/myapp

  deploy-dev:
    runs-on: windows-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: ${{env.DOTNET_ROOT}}/myapp

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      id: arm-deploy
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG_DEV }}
        template: ./deployment/backend.json
        parameters: ./deployment/backend.dev.params.json
          sqlAdministratorLogin=${{ secrets.SQLADMINISTRATORLOGIN_DEV }}
          sqlAdministratorLoginPassword=${{ secrets.SQLADMINISTRATORLOGINPASSWORD_DEV }}
          jwtTokenSecret=${{ secrets.JWTTOKENSECRET_DEV }}
          sendgridEmailApiKey=${{ secrets.SENDGRIDEMAILAPIKEY_DEV }}

    - name: Get WebApp publishing profile
      run: |
        $publishingProfile = $( `
          az webapp deployment list-publishing-profiles `
            --name ${{ steps.arm-deploy.outputs.webAppName }} `
            --resource-group ${{ secrets.AZURE_RG_DEV }} `
            --subscription ${{ secrets.AZURE_SUBSCRIPTION }} `
            --xml `
        ) && `
        echo ::add-mask::$publishingProfile && `
        echo ::set-env name=PUBLISHING_PROFILE::$publishingProfile
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ steps.arm-deploy.outputs.webAppName }}'
        slot-name: 'production'
        publish-profile: ${{ env.PUBLISHING_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/myapp
`

**Comment by JaMatus** [comment]
@t-dedah sure 🙂   here is the release workflow file:

```
name: DEV .NET Core CD ARM template

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{env.DOTNET_ROOT}}/myapp

  deploy-dev:
    runs-on: windows-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: ${{env.DOTNET_ROOT}}/myapp

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      id: arm-deploy
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG_DEV }}
        template: ./deployment/backend.json
        parameters: ./deployment/backend.dev.params.json
          sqlAdministratorLogin=${{ secrets.SQLADMINISTRATORLOGIN_DEV }}
          sqlAdministratorLoginPassword=${{ secrets.SQLADMINISTRATORLOGINPASSWORD_DEV }}
          jwtTokenSecret=${{ secrets.JWTTOKENSECRET_DEV }}
          sendgridEmailApiKey=${{ secrets.SENDGRIDEMAILAPIKEY_DEV }}

    - name: Get WebApp publishing profile
      run: |
        $publishingProfile = $( `
          az webapp deployment list-publishing-profiles `
            --name ${{ steps.arm-deploy.outputs.webAppName }} `
            --resource-group ${{ secrets.AZURE_RG_DEV }} `
            --subscription ${{ secrets.AZURE_SUBSCRIPTION }} `
            --xml `
        ) && `
        echo ::add-mask::$publishingProfile && `
        echo ::set-env name=PUBLISHING_PROFILE::$publishingProfile
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ steps.arm-deploy.outputs.webAppName }}'
        slot-name: 'production'
        publish-profile: ${{ env.PUBLISHING_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/myapp

```
