### ISSUE TITLE
Task fails for bicep template deploy

### ISSUE THREAD

**Issue by vermegi** [Azure/arm-deploy#70]
Using arm-deploy@v1 to deploy a bicep ARM template: 

```YAML
on: [push]
name: AzureBicepSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: github-action-arm-rg
        template: ./main.bicep
        parameters: environmentType=Test
```

Task fails with following output: 

Run azure/arm-deploy@v1
  with:
    resourceGroupName: github-action-arm-rg
    template: ./main.bicep
    parameters: environmentType=Test
    failOnStdErr: true
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
Validating template...
Warning: WARNING: Build succeeded: 0 Warning(s), 0 Error(s)

Creating deployment...
Error: WARNING: Build succeeded: 0 Warning(s), 0 Error(s)

Error: Deployment process failed as some lines were written to stderr

---

This error seems to be similar to #48
