### ISSUE TITLE
Azure Bicep Outputs Are Not Parsed

### ISSUE THREAD

**Issue by AErmie** [Azure/arm-deploy#78]
When using GitHub Actions to deploy infrastructure in Azure, specifically via Azure Bicep templates, even though the template may have outputs defined, this is not parsed correctly and therefore no information is returned to the console.

![AzureBicep-GHAction-Output](https://user-images.githubusercontent.com/10376796/130477198-3b99b9e0-8cc2-4646-a6f5-a864f57bce81.png)

## Sample Bicep Code

``` bicep
param accountPrefix string = 'test'
param location string = 'eastus'
param utc string = utcNow()

var storageAccountName_var = '${replace(replace(replace(accountPrefix, '.', ''), '_', ''), '-', '')}ghedata${utc}'
var storageAccountType = 'Premium_LRS'

resource storageAccount 'Microsoft.Storage/storageAccounts@2021-01-01' = {
  name: toLower(take(storageAccountName_var, 24))
  location: location
  sku: {
    name: storageAccountType
  }
  kind: 'StorageV2'
}

output storageAccount_Name string = storageAccount.name
output storageAccount_Location string = storageAccount.location
output storageAccount_SKUName string = storageAccount.sku.name
output storageAccount_Kind string = storageAccount.kind
```

## Sample GitHub Actions Workflow

``` yaml
name: Deploy GHES using Azure Bicep

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      gh_handle:
        description: 'What is your GitHub handle?'
        required: true
      accountPrefix:
        description: 'Unique prefix for your Storage Account and VM name. Must be all lower case letters or numbers. No spaces or special characters.'
        required: true
      location:
        description: "What Azure region to deploy to (ie. 'eastus', 'canadacentral')"
        default: 'eastus'
        required: true
      ghes_version:
        description: "What version of GHES do you need (ie. 2.22.19, 3.0.13, 3.1.5)?"
        default: 'latest'
        required: true

jobs:
  create_resource_group:
    name: Create Resource Group
    runs-on: ubuntu-latest
    steps:
      # Log into Azure
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run:
          az group create --name 'GHES-${{ github.event.inputs.gh_handle }}' --location ${{ github.event.inputs.location }} --tags [Owner[= ${{ github.event.inputs.gh_handle }} ]]

  deploy_ghes:
    name: Deploy GHES
    runs-on: ubuntu-latest
    needs: [create_resource_group]
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@main

      # Log into Azure
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: Deploy GHES
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: GHES-${{ github.event.inputs.gh_handle }}
          template: ./Bicep/main.bicep
          parameters: ./Bicep/bicep.parameters.json accountPrefix=${{ github.event.inputs.accountPrefix }} ghesversion=${{ github.event.inputs.ghes_version }}
          failOnStdErr: false
```

**Comment by t-dedah** [comment]
@AErmie Raised PR to support these logs. https://github.com/Azure/arm-deploy/pull/79

If the issue needs a quick fix then enable debug logs in the repository. Create a new repo secret with `ACTIONS_STEP_DEBUG ` set to `true`

https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging

**Comment by t-dedah** [comment]
Hi @AErmie, can you try rerunning the workflow and see what outputs are you getting as we tried running the above template and the outputs were parsed correctly for us?


```
Parsing outputs...

::set-output name=storageAccount_Kind::StorageV2

::set-output name=storageAccount_Location::eastasia


::set-output name=storageAccount_Name::deepak21

::set-output name=storageAccount_SKUName::Premium_LRS
```

If the error still continues set this environment secret `ACTIONS_STEP_DEBUG` to `true` and confirm if the debug logs are correct.

**Comment by AErmie** [comment]
Hey @t-dedah, when I have `ACTIONS_STEP_DEBUG` enabled, I see that it does parse the outputs (and I can subsequently use those outputs in another step). 

![BicepOutputs](https://user-images.githubusercontent.com/10376796/131518821-aee739a7-d050-4b2c-9959-db8bdbc8c2f8.png)

But what I was referring to, are the outputs from the Bicep template. Similar to Terraform, if you have `outputs`, those will be written to the console as part of the template execution. 

When the GitHub Action says "parsing outputs" I (by default) assume it's the outputs defined in the template, and expect it to be visible in the console (without `DEBUG` enabled).

**Comment by t-dedah** [comment]
@AErmie Can yo please show me what outputs are you expecting?

The purple logs are from DEBUG whereas the white logs are your normal logs so everything after `parsing outputs...` is consoled twice.

**Comment by AErmie** [comment]
Hey @t-dedah, sorry if I wasn't clear. I'm referring to the outputs in the Bicep file...

``` bicep
output storageAccount_Name string = storageAccount.name
output storageAccount_Location string = storageAccount.location
output storageAccount_SKUName string = storageAccount.sku.name
output storageAccount_Kind string = storageAccount.kind
```

My expectation is similar to what Terraform produces when you run `terraform apply`, where it will write out to the console the actual values of the resources. 

When you have `debug` turned off, you don't actually see any of the outputs. So, unless you know it's still actually there under the covers, a user will think it's not.

**Comment by t-dedah** [comment]
Hi @AErmie , there was some misunderstanding, the above output is an expected behaviour. We are not printing any output as part of parsing process. If the outputs needs to be printed then we should explicitly do that in next step using this https://github.com/Azure/arm-deploy#another-example-on-how-to-use-this-action-to-get-the-output-of-arm-template


``` yml
      - name: Deploy GHES
        id: deploy_ghes
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: GHES-${{ github.event.inputs.gh_handle }}
          template: ./Bicep/main.bicep
          parameters: ./Bicep/bicep.parameters.json accountPrefix=${{ github.event.inputs.accountPrefix }} ghesversion=${{ github.event.inputs.ghes_version }}
          failOnStdErr: false
```

```yml
- run: echo ${{ steps.deploy_ghes.outputs.storageAccount_Name }}
```

This behaviour was implemented in order to save us from printing secrets by mistake.
