### ISSUE TITLE
ARM template outputs containing resource ids sanitized

### ISSUE THREAD

**Issue by stephenmahood** [Azure/arm-deploy#94]
When using the Azure Login GitHub action with the creds parameter:
```
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
```
secrets.AZURE_CREDENTIALS:
```
{
    "clientId": "<GUID>",
    "clientSecret": "<GUID>",
    "subscriptionId": "<GUID>",
    "tenantId": "<GUID>",
    (...)
  }
```
 and then deploying an ARM template with the arm-deploy action that returns a resourceId as a template output, GitHub sanitizes the step output  due to the subscriptionId within the resourceId being present within the AZURE_CREDENTIALS secret.
